### ISSUE TITLE
Reading string descriptors from UsbDevice

### ISSUE THREAD

**Issue by Anthonywolfe** [nefarius/Nefarius.Drivers.WinUSB#5]
Hi, 
I'm interested in porting my application over from WinUSBNet, However I made some custom modifications to it to support the device I'm trying to communicate with. Thankfully it should be relatively simple, I just need to expose [ReadStringDescriptor in ](https://github.com/nefarius/Nefarius.Drivers.WinUSB/blob/797ffd1f23b8ef3359d50d5542b0c1382b4b3fa9/WinUSBNet/API/WinUSBDevice.cs#L87) to UsbDevice so I can read from some custom string descriptors on the device. 

As this would be more involved than the PR I did for the USBPipePolicy I thought I'd ask how you'd want the API for it to look.

**Comment by nefarius** [comment]
So expose like a ReadStringDescriptor on USBDevice? Sounds useful indeed! Also bear in mind we're currently modernising the master branch and optimise it for speed so breaking changes might occur!

**Comment by Anthonywolfe** [comment]
Ah, Sorry I didn't notice the comment as github didn't notify me of it. I've submitted a PR over here https://github.com/nefarius/Nefarius.Drivers.WinUSB/pull/6 but let me know if I need to make any adjustments.

**Comment by nefarius** [comment]
All good, merged the fun 👍 Anything else? 😉

**Comment by Anthonywolfe** [comment]
I think that should just about do it thanks!

**Comment by nefarius** [comment]
Published new nuget.
