### ISSUE TITLE
Support for .NET Framework 4.8

### ISSUE THREAD

**Issue by josesimoes** [nefarius/Nefarius.Drivers.WinUSB#7]
Hi,

Any chance we can have back support for .NET Framework?
I'm OK with submitting a PR for this if you're willing to consider it.

**Comment by nefarius** [comment]
Is it still relevant? Well, be my guest with the PR, I see no harm in it.

**Comment by josesimoes** [comment]
Yes! Legacy code to maintain that needs to keep using it...

**Comment by nefarius** [comment]
If you have any questions about the fork or wanna discuss stuff [be my guest on our Discord](https://vigem.org/Community-Support/).
